export const games = [
  {
    name: 'NBA 2K25 (PS5)',
    image: '/001.jpg',
    developer: 'Visual Concepts',
    console: 'PS5',
    genre: 'Sports',
    year: '2024',
    price: 90,
  },
  {
    name: 'NBA 2K25 (XBOX)',
    image: '/002.jpg',
    developer: 'Visual Concepts',
    console: 'XBOX',
    genre: 'Sports',
    year: '2024',
    price: 90,
  },
  {
    name: 'EA FC25 (PS5)',
    image: '/003.jpg',
    developer: 'Electronic Arts',
    console: 'PS5',
    genre: 'Sports',
    year: '2024',
    price: 90,
  },
  {
    name: 'EA FC25 (XBOX)',
    image: '/004.jpg',
    developer: 'Electronic Arts',
    console: 'XBOX',
    genre: 'Sports',
    year: '2024',
    price: 90,
  },
  {
    name: 'GTA V (PS5)',
    image: '/005.jpg',
    developer: 'Rockstar Games',
    console: 'PS5',
    genre: 'Action/Adventure',
    year: '2013',
    price: 50,
  },
  {
    name: 'GTA V (XBOX)',
    image: '/006.jpg',
    developer: 'Rockstar Games',
    console: 'XBOX',
    genre: 'Action/Adventure',
    year: '2013',
    price: 50,
  },
  {
    name: 'Elden Ring (PS5)',
    image: '/007.jpg',
    developer: 'FromSoftware & Bandai Namco',
    console: 'PS5',
    genre: 'Action/Role Playing Game',
    year: '2022',
    price: 80,
  },
  {
    name: 'Elden Ring (XBOX)',
    image: '/008.jpg',
    developer: 'FromSoftware & Bandai Namco',
    console: 'XBOX',
    genre: 'Action/Role Playing Game',
    year: '2022',
    price: 80,
  },
  {
    name: 'Call of Duty Black OPS 6 (PS5)',
    image: '/009.jpg',
    developer: 'Activision',
    console: 'PS5',
    genre: 'Shooter',
    year: '2024',
    price: 90,
  },
  {
    name: 'Call of Duty Black OPS 6 (XBOX)',
    image: '/010.jpg',
    developer: 'Activision',
    console: 'XBOX',
    genre: 'Shooter',
    year: '2024',
    price: 90,
  },
  {
    name: 'F1 24 (PS5)',
    image: '/011.jpg',
    developer: 'Codemasters & Electronic Arts',
    console: 'PS5',
    genre: 'Racing',
    year: '2024',
    price: 90,
  },
  {
    name: 'F1 24 (XBOX)',
    image: '/012.jpg',
    developer: 'Codemasters & Electronic Arts',
    console: 'XBOX',
    genre: 'Racing',
    year: '2024',
    price: 90,
  }
]
export const genres = ['Action', 'Adventure', 'Racing', 'Role Playing Game', 'Shooter', 'Sports']
export const developers = ['Activision', 'Bandai Namco', 'Codemasters', 'Electronic Arts', 'FromSoftware', 'Visual Concepts']
export const consoles = ['PS5', 'XBOX']